### ISSUE TITLE
Exception when attempting to run Cloverage on a compojure service

### ISSUE THREAD

**Issue by ricardojmendez** [cloverage/cloverage#164]
Cloverage 1.0.9 dies when attempting to run on a Compojure service which uses authentication.

Attaching a minimal case. Archive includes a git repository with two commits: the initial template code where Cloverage works, followed by a commit adding authentication which causes it to die. Cloverage dies even if the APIs added are not tested.

This seems related to #53.

Trace:

```
	at cloverage.instrument$instrument$fn__19680.invoke(instrument.clj:432)
	at cloverage.instrument$instrument.invokeStatic(instrument.clj:424)
	at cloverage.instrument$instrument.invoke(instrument.clj:403)
	at cloverage.coverage$_main$fn__20452.invoke(coverage.clj:254)
	at cloverage.coverage$_main.invokeStatic(coverage.clj:251)
	at cloverage.coverage$_main.doInvoke(coverage.clj:213)
	at clojure.lang.RestFn.invoke(RestFn.java:1289)
	at clojure.lang.Var.invoke(Var.java:501)
	at user$eval19186.invokeStatic(form-init3717775251225065018.clj:1)
	at user$eval19186.invoke(form-init3717775251225065018.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
Caused by: java.lang.ExceptionInInitializerError, compiling:(swag/routes/services.clj:69:5)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3657)
	at clojure.lang.Compiler$BodyExpr.eval(Compiler.java:6019)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3651)
	at clojure.lang.Compiler$BodyExpr.eval(Compiler.java:6019)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3651)
	at clojure.lang.Compiler$BodyExpr.eval(Compiler.java:6019)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:451)
	at clojure.lang.Compiler.eval(Compiler.java:6932)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.eval(Compiler.java:6890)
	at clojure.core$eval.invokeStatic(core.clj:3105)
	at clojure.core$eval.invoke(core.clj:3101)
	at cloverage.instrument$instrument$fn__19680$fn__19681.invoke(instrument.clj:427)
	at cloverage.instrument$instrument$fn__19680.invoke(instrument.clj:425)
	... 26 more
Caused by: java.lang.ExceptionInInitializerError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at clojure.lang.Compiler$ObjExpr.eval(Compiler.java:4913)
	at clojure.lang.Compiler$MetaExpr.eval(Compiler.java:2654)
	at clojure.lang.Compiler$BodyExpr.eval(Compiler.java:6019)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3651)
	... 39 more
Caused by: java.lang.IllegalArgumentException: No matching ctor found for class clojure.lang.AFunction$1
	at clojure.lang.Reflector.invokeConstructor(Reflector.java:163)
	at clojure.lang.LispReader$EvalReader.invoke(LispReader.java:1120)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:691)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:196)
	at clojure.lang.LispReader.read(LispReader.java:185)
	at clojure.lang.RT.readString(RT.java:1835)
	at clojure.lang.RT.readString(RT.java:1830)
	at swag.routes.services$fn__20625.<clinit>(swag/routes/services.clj:69)
	... 48 more
```

[swag.zip](https://github.com/cloverage/cloverage/files/565995/swag.zip)

**Comment by lvh** [comment]
Thanks! This isn't the case in 1.0.8, right?

**Comment by ricardojmendez** [comment]
Just tried it with 1.0.8, I get the same exception.

**Comment by rbuchmann** [comment]
Hi @ricardojmendez , I had the same problem and was able to fix it. 

```
(defmethod restructure-param :auth-rules
  [_ rule acc]
  (update-in acc [:middleware] conj [wrap-restricted rule]))
```

expands wrap-restricted into a function, not code. It should be `wrap-restricted. The vital hint came from #53.

**Comment by PayalGodse** [comment]
@rbuchmann 
I am facing same authentication problem with cloverage and compojure? I tried adding ^method to test.core.  But getting a runtime exception 'Unable to resolve symbol: restructure-param in this context'. Am I missing something?

**Comment by rbuchmann** [comment]
@PayalGodse that sounds like you're just missing    
```
(:require [compojure.api.meta :refer [restructure-param]]) 
```
somewhere.

**Comment by PayalGodse** [comment]
@rbuchmann thanks, got this.. but still I am not able to figure out authentication issue as  it throws Cookie rejected errors.

**Comment by rbuchmann** [comment]
@PayalGodse sounds more like a usage error than a bug in compojure-api or cloverage, I suggest you ask on IRC or Clojurians with some relevant code.

**Comment by ricardojmendez** [comment]
Closing, @rbuchmann's [workaround](https://github.com/cloverage/cloverage/issues/164#issuecomment-281673566) solves the problem.
