### ISSUE TITLE
lein cloverage --junit fails if target/coverage/ directory is missing: target/coverage/junit.xml (No such file or directory)

### ISSUE THREAD

**Issue by urzds** [cloverage/cloverage#167]
```
# rm -fr target
# lein cloverage --junit
WARNING: reader-conditional already refers to: #'clojure.core/reader-conditional in namespace: clojure.tools.reader.impl.utils, being replaced by: #'clojure.tools.reader.impl.utils/reader-conditional
WARNING: tagged-literal already refers to: #'clojure.core/tagged-literal in namespace: clojure.tools.reader.impl.utils, being replaced by: #'clojure.tools.reader.impl.utils/tagged-literal
Loading namespaces:  (...)
Test namespaces:  (....test-handler)
Loaded  ... .
Instrumented namespaces.
Exception in thread "main" java.io.FileNotFoundException: target/coverage/junit.xml (No such file or directory), compiling:(/tmp/form-init7444469319178050286.clj:1:73)
        at clojure.lang.Compiler.load(Compiler.java:7391)
        at clojure.lang.Compiler.loadFile(Compiler.java:7317)
        at clojure.main$load_script.invokeStatic(main.clj:275)
        at clojure.main$init_opt.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invoke(main.clj:277)
        at clojure.main$initialize.invokeStatic(main.clj:308)
        at clojure.main$null_opt.invokeStatic(main.clj:342)
        at clojure.main$null_opt.invoke(main.clj:339)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: target/coverage/junit.xml (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at clojure.java.io$fn__9522.invokeStatic(io.clj:230)
        at clojure.java.io$fn__9522.invoke(io.clj:230)
        at clojure.java.io$fn__9459$G__9428__9466.invoke(io.clj:69)
        at clojure.java.io$fn__9496.invokeStatic(io.clj:166)
        at clojure.java.io$fn__9496.invoke(io.clj:166)
        at clojure.java.io$fn__9472$G__9424__9479.invoke(io.clj:69)
        at clojure.java.io$writer.invokeStatic(io.clj:119)
        at clojure.java.io$writer.doInvoke(io.clj:104)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at cloverage.coverage$eval2997$fn__2998$fn__2999.invoke(coverage.clj:195)
        at cloverage.coverage$_main.invokeStatic(coverage.clj:263)
        at cloverage.coverage$_main.doInvoke(coverage.clj:213)
        at clojure.lang.RestFn.invoke(RestFn.java:930)
        at clojure.lang.Var.invoke(Var.java:469)
        at user$eval5.invokeStatic(form-init7444469319178050286.clj:1)
        at user$eval5.invoke(form-init7444469319178050286.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6917)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        ... 14 more
```

The problem does not occur, if I create `target/coverage/` before running `lein coverage --junit`:
```
# rm -fr target
# mkdir -p target/coverage
# lein cloverage --junit
...
Instrumented namespaces.
Ran tests.
...
```

**Comment by rm-hull** [comment]
Hello @urzds, which version is this with?

I think the fix is quite straightforward, there is a `(.mkdirs (io/file output))` which needs to be moved before the runner-fn is invoked.
