### ISSUE TITLE
Use of Datomic triggers past issue

### ISSUE THREAD

**Issue by ds2643** [cloverage/cloverage#173]
I encountered the following error while attempting to run `cloverage` on a project that heavily uses [`datomic`](http://docs.datomic.com/clojure/):

```
ARNING: reader-conditional already refers to: #'clojure.core/reader-conditional in namespace: clojure.tools.reader.impl.utils, being replaced by: #'clojure.tools.reader.impl.utils/reader-conditional
WARNING: tagged-literal already refers to: #'clojure.core/tagged-literal in namespace: clojure.tools.reader.impl.utils, being replaced by: #'clojure.tools.reader.impl.utils/tagged-literal
Loading namespaces:  (sample.core)
Test namespaces:  (sample.core-test)
Exception in thread "main" clojure.lang.ExceptionInfo: No reader function for tag id {:type :reader-exception, :line 8, :column 35}, compiling:(/private/var/folders/fp/fs5dlz1x47ggt8r2_1pmxv7c0000gn/T/form-init3532539346039915584.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
```

To make helping as painless as possible, I've isolated the issue to the following snippet:
```clojure
(ns sample.core
  (:gen-class)
  (:require [datomic.api :refer [q] :as d]
            :reload-all))

(defn add-person
  [conn id]
  (d/transact conn [{:db/id #db/id[:db.part/user -1000001]
                     :person/id id}]))
```

It seems like this may be some issue related to the use of the reader by Cloverage. Additionally, it may be worth pointing out that this seems to be a [recurrent issue](https://github.com/LightTable/LightTable/issues/376) in the context of some other projects.

An ideas how to resolve this issue?

**Comment by ds2643** [comment]
Worth noting is that this error is triggered with the use of Cloverage `1.0.9`. A different set of errors, which I'll prepare posts on soon, occur with the use of Cloverage `1.0.0`.

**Comment by lvh** [comment]
Why did this get closed?

**Comment by timgilbert** [comment]
It's worth noting that this may be an incorrect use of the datomic reader literals - datomic provides a `(d/tempid)` function meant to be used in functions like this (or in more recent releases, you can use a string as the tempid). The `#db/id` bit is resolved at read-time, when sample-ns.core is compiled, which means that every time `(add-person)` is invoked it will use the same value.

**Comment by lvh** [comment]
@timgilbert is the bug in cloverage or in the code it fails to instrument?
