### ISSUE TITLE
Exception in thread "main" clojure.lang.ExceptionInfo: No reader function for tag id {:type :reader-exception, :line 100, :column 32},

### ISSUE THREAD

**Issue by kenrestivo-stem** [cloverage/cloverage#174]
```
Exception in thread "main" clojure.lang.ExceptionInfo: No reader function for tag id {:type :reader-exception, :line 100, :column 32}, compiling:(/foo/target/da3d743adbf84f6e0389639ca709e8174cd98efc-init.clj:1:5)
	at clojure.lang.Compiler.load(Compiler.java:7442)
	at clojure.lang.Compiler.loadFile(Compiler.java:7368)
	at clojure.main$load_script.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invokeStatic(main.clj:279)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invokeStatic(main.clj:310)
	at clojure.main$null_opt.invokeStatic(main.clj:344)
	at clojure.main$null_opt.invoke(main.clj:341)
	at clojure.main$main.invokeStatic(main.clj:423)
	at clojure.main$main.doInvoke(main.clj:386)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: No reader function for tag id {:type :reader-exception, :line 100, :column 32}
	at clojure.core$ex_info.invokeStatic(core.clj:4725)
	at clojure.core$ex_info.invoke(core.clj:4725)
	at clojure.tools.reader.reader_types$reader_error.invokeStatic(reader_types.clj:331)
	at clojure.tools.reader.reader_types$reader_error.doInvoke(reader_types.clj:327)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at clojure.tools.reader$read_tagged.invokeStatic(reader.clj:824)
	at clojure.tools.reader$read_tagged.invoke(reader.clj:811)
	at clojure.tools.reader$read_dispatch.invokeStatic(reader.clj:71)
	at clojure.tools.reader$read_dispatch.invoke(reader.clj:66)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:889)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:195)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:188)
	at clojure.tools.reader$read_map.invokeStatic(reader.clj:242)
	at clojure.tools.reader$read_map.invoke(reader.clj:238)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:889)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:195)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:188)
	at clojure.tools.reader$read_vector.invokeStatic(reader.clj:226)
	at clojure.tools.reader$read_vector.invoke(reader.clj:222)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:889)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:195)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:188)
	at clojure.tools.reader$read_list.invokeStatic(reader.clj:208)
	at clojure.tools.reader$read_list.invoke(reader.clj:204)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:889)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:872)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$wrapping_reader$fn__688.invoke(reader.clj:367)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:889)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:195)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:188)
	at clojure.tools.reader$read_list.invokeStatic(reader.clj:208)
	at clojure.tools.reader$read_list.invoke(reader.clj:204)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:889)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:195)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:188)
	at clojure.tools.reader$read_list.invokeStatic(reader.clj:208)
	at clojure.tools.reader$read_list.invoke(reader.clj:204)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:889)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read.invokeStatic(reader.clj:938)
	at clojure.tools.reader$read.invoke(reader.clj:915)
	at cloverage.instrument$instrument$fn__958.invoke(instrument.clj:410)
	at cloverage.instrument$instrument.invokeStatic(instrument.clj:409)
	at cloverage.instrument$instrument.invoke(instrument.clj:403)
	at cloverage.coverage$_main$fn__1822.invoke(coverage.clj:254)
	at cloverage.coverage$_main.invokeStatic(coverage.clj:251)
	at cloverage.coverage$_main.doInvoke(coverage.clj:213)
	at clojure.lang.RestFn.invoke(RestFn.java:3894)
	at clojure.lang.Var.invoke(Var.java:676)
	at user$eval13.invokeStatic(da3d743adbf84f6e0389639ca709e8174cd98efc-init.clj:1)
	at user$eval13.invoke(da3d743adbf84f6e0389639ca709e8174cd98efc-init.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6978)
	at clojure.lang.Compiler.eval(Compiler.java:6968)
	at clojure.lang.Compiler.load(Compiler.java:7430)
	... 12 more
```

:(

Seems related to
https://github.com/cloverage/cloverage/issues/173 and https://github.com/LightTable/LightTable/issues/244 .

**Comment by dazld** [comment]
It's an old issue, but just wanted to chime in that had a similar problem, and the issue was the readers hadn't been loaded (in my case, the datomic ones). I had to explicitly bind the readers when we were slurping in EDN, and then all was ok - ie:

```clojure

(ns foo.bar.baz
  (:require [datomic.api :as d]

            datomic.db
            datomic.function
            datomic.codec))

; ... 
(let [readers {:readers (merge
                            *data-readers*
                            {'db/id  datomic.db/id-literal
                             'db/fn  datomic.function/construct
                             'base64 datomic.codec/base-64-literal})}
        read (partial clojure.edn/read-string readers)]
    (if-let [file (some-resource url)]
        (->> file
             slurp
             read)
; .... etc
```
