### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by micahasmith** [cloverage/cloverage#175]
When i run lein cloverage on my project, i get the following:

```
Loaded  gooten-store-api.specs.globals  .
Exception in thread "main" java.lang.IllegalArgumentException: Cannot find resource , compiling:(/private/var/folders/mf/n6g7nwd119vbmkg80d0yvm380000gn/T/form-init6213264325851030205.clj:1:125)
        at clojure.lang.Compiler.load(Compiler.java:7391)
        at clojure.lang.Compiler.loadFile(Compiler.java:7317)
        at clojure.main$load_script.invokeStatic(main.clj:275)
        at clojure.main$init_opt.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invoke(main.clj:277)
        at clojure.main$initialize.invokeStatic(main.clj:308)
        at clojure.main$null_opt.invokeStatic(main.clj:342)
        at clojure.main$null_opt.invoke(main.clj:339)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
```
I cannot tell what its trying to load...?

**Comment by rm-hull** [comment]
Can you share the project where you're seeing this or are able to reproduce it on a simple test project?

**Comment by lvh** [comment]
Closing this since there's no reproducer so it's not actionable, and it's nearly a decade old.
