### ISSUE TITLE
`lein cloverage` fails when :target-path is set to somewhere else

### ISSUE THREAD

**Issue by Sh4pe** [cloverage/cloverage#190]
When running `lein cloverage` on a brand new project (i.e. one where the `target` subdirectory does not yet exist), it fails with an exception. You can use these steps to reproduce the problem (use the attached [patch.txt](https://github.com/cloverage/cloverage/files/1252070/patch.txt)):

```bash
$ lein new foo
$ cd foo
$ patch project.clj < patch.txt
$ lein cloverage
...
Exception in thread "main" java.io.FileNotFoundException: target/coverage/coverage.css (No such file or directory), compiling:(/private/var/folders/vy/xbv3vmcd74x8wnljh8md7sb00000gp/T/form-init1622130162592745541.clj:1:124)
	at clojure.lang.Compiler.load(Compiler.java:7142)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: target/coverage/coverage.css (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at clojure.java.io$fn__8742.invoke(io.clj:332)
	at clojure.lang.MultiFn.invoke(MultiFn.java:236)
	at clojure.java.io$copy.doInvoke(io.clj:396)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at cloverage.report$html_report.invoke(report.clj:208)
	at cloverage.coverage$_main.doInvoke(coverage.clj:277)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at clojure.lang.Var.invoke(Var.java:388)
	at user$eval5.invoke(form-init1622130162592745541.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6693)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	... 11 more
```

The workaround would be to `mkdir target` before running `lein cloverage`. It would be nice that this would work without having to create `target` first. In my setup, I'd like not to depend on a otherwise useless `target` directory.

**Comment by lvh** [comment]
On https://github.com/cloverage/cloverage/blob/84026bf3b51747aba53ec6e198d0b89f7fee891c/cloverage/src/cloverage/coverage.clj#L288 the path to the output file is created, so that's strange.

However, the default output is hardcoded as `target/...`. Can you try setting `-o /tmp/whatever`?

**Comment by Sh4pe** [comment]
That works:
```bash
$ lein cloverage -o /tmp/foo/target
# produces HTML output
```

So if `-o` is not supplied, would it be a good idea to use whatever is set to `:target-path` in `project.clj` as default?

**Comment by lvh** [comment]
Yep! I'd be happy to review a patch and cut a release.

**Comment by Sh4pe** [comment]
Alright. I see when I can make the time and I'll let you know then.

**Comment by Sh4pe** [comment]
I won't have the time to fix this, hence I close this issue.

**Comment by lvh** [comment]
I appreciate you may not have the time, but someone else might, so I'd prefer to keep it open.
