### ISSUE TITLE
Cloverage fails when using Datomic reader literals

### ISSUE THREAD

**Issue by kenrestivo-stem** [cloverage/cloverage#197]
```
Exception in thread "main" clojure.lang.ExceptionInfo: No reader function for tag id {:type :reader-exception, :line 48, :column 37}, compiling:(/home/src/foo/target/7d22ecc0eebbeaa232e98bcb41451c2af08ba6b2-init.clj:1:5)
	at clojure.lang.Compiler.load(Compiler.java:7442)
	at clojure.lang.Compiler.loadFile(Compiler.java:7368)
	at clojure.main$load_script.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invokeStatic(main.clj:279)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invokeStatic(main.clj:310)
	at clojure.main$null_opt.invokeStatic(main.clj:344)
	at clojure.main$null_opt.invoke(main.clj:341)
	at clojure.main$main.invokeStatic(main.clj:423)
	at clojure.main$main.doInvoke(main.clj:386)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: No reader function for tag id {:type :reader-exception, :line 48, :column 37}
	at clojure.core$ex_info.invokeStatic(core.clj:4725)
	at clojure.core$ex_info.invoke(core.clj:4725)
	at clojure.tools.reader.reader_types$reader_error.invokeStatic(reader_types.clj:331)
	at clojure.tools.reader.reader_types$reader_error.doInvoke(reader_types.clj:327)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at clojure.tools.reader$read_tagged.invokeStatic(reader.clj:824)
	at clojure.tools.reader$read_tagged.invoke(reader.clj:811)
	at clojure.tools.reader$read_dispatch.invokeStatic(reader.clj:71)
	at clojure.tools.reader$read_dispatch.invoke(reader.clj:66)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:889)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:195)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:188)
	at clojure.tools.reader$read_map.invokeStatic(reader.clj:242)
	at clojure.tools.reader$read_map.invoke(reader.clj:238)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:889)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:195)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:188)
	at clojure.tools.reader$read_vector.invokeStatic(reader.clj:226)
	at clojure.tools.reader$read_vector.invoke(reader.clj:222)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:889)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:195)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:188)
	at clojure.tools.reader$read_list.invokeStatic(reader.clj:208)
	at clojure.tools.reader$read_list.invoke(reader.clj:204)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:889)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:195)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:188)
	at clojure.tools.reader$read_list.invokeStatic(reader.clj:208)
	at clojure.tools.reader$read_list.invoke(reader.clj:204)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:889)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:195)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:188)
	at clojure.tools.reader$read_list.invokeStatic(reader.clj:208)
	at clojure.tools.reader$read_list.invoke(reader.clj:204)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:889)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:870)
	at clojure.tools.reader$read.invokeStatic(reader.clj:938)
	at clojure.tools.reader$read.invoke(reader.clj:915)
	at cloverage.instrument$instrument$fn__958.invoke(instrument.clj:410)
	at cloverage.instrument$instrument.invokeStatic(instrument.clj:409)
	at cloverage.instrument$instrument.invoke(instrument.clj:403)
	at cloverage.coverage$_main$fn__1822.invoke(coverage.clj:254)
	at cloverage.coverage$_main.invokeStatic(coverage.clj:251)
	at cloverage.coverage$_main.doInvoke(coverage.clj:213)
	at clojure.lang.RestFn.invoke(RestFn.java:3894)
	at clojure.lang.Var.invoke(Var.java:676)
	at user$eval13.invokeStatic(7d22ecc0eebbeaa232e98bcb41451c2af08ba6b2-init.clj:1)
	at user$eval13.invoke(7d22ecc0eebbeaa232e98bcb41451c2af08ba6b2-init.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6978)
	at clojure.lang.Compiler.eval(Compiler.java:6968)
	at clojure.lang.Compiler.load(Compiler.java:7430)
	... 12 more
```

The offending function that causes this error (found through bifurcation; the error gives no indication where it might be coming from or caused by), appears to be
```clojure
(defn read-datomic-edn
  [edn-file]
  (->> edn-file
       slurp
       (clojure.edn/read-string {:readers *data-readers*})))
```

Can't live without this function; need to run migrations on the DB. Any idea how to make cloverage cope with it?

**Comment by kenrestivo-stem** [comment]
Tried manually putting the readers in. Still fails :(

```clojure
(defn read-datomic-edn
  [edn-file]
  (->> edn-file
       slurp
       (edn/read-string {:readers (merge
                                   *data-readers*
                                   ;; XXX still does not help. at all. at all.
                                   {'db/id #'datomic.db/id-literal,
                                    'db/fn #'datomic.function/construct,
                                    'base64 #'datomic.codec/base-64-literal})})))
```

```
Exception in thread "main" clojure.lang.ExceptionInfo: [line 48, col 37] No reader function for tag db/id. {:type :reader-exception, :ex-kind :reader-error, :file nil, :line 48, :col 37}, compiling:(/home/src/builds-manager/target/74780825e58d49516ee72081470407c9461ba94a-init.clj:1:5)
	at clojure.lang.Compiler.load(Compiler.java:7442)
	at clojure.lang.Compiler.loadFile(Compiler.java:7368)
	at clojure.main$load_script.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invokeStatic(main.clj:279)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invokeStatic(main.clj:310)
	at clojure.main$null_opt.invokeStatic(main.clj:344)
	at clojure.main$null_opt.invoke(main.clj:341)
	at clojure.main$main.invokeStatic(main.clj:423)
	at clojure.main$main.doInvoke(main.clj:386)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: [line 48, col 37] No reader function for tag db/id. {:type :reader-exception, :ex-kind :reader-error, :file nil, :line 48, :col 37}
	at clojure.core$ex_info.invokeStatic(core.clj:4725)
	at clojure.core$ex_info.invoke(core.clj:4725)
	at clojure.tools.reader.impl.errors$throw_ex.invokeStatic(errors.clj:34)
	at clojure.tools.reader.impl.errors$throw_ex.doInvoke(errors.clj:24)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at clojure.tools.reader.impl.errors$reader_error.invokeStatic(errors.clj:40)
	at clojure.tools.reader.impl.errors$reader_error.doInvoke(errors.clj:36)
	at clojure.lang.RestFn.invoke(RestFn.java:460)
	at clojure.tools.reader.impl.errors$throw_unknown_reader_tag.invokeStatic(errors.clj:212)
	at clojure.tools.reader.impl.errors$throw_unknown_reader_tag.invoke(errors.clj:211)
	at clojure.tools.reader$read_tagged.invokeStatic(reader.clj:859)
	at clojure.tools.reader$read_tagged.invoke(reader.clj:846)
	at clojure.tools.reader$read_dispatch.invokeStatic(reader.clj:71)
	at clojure.tools.reader$read_dispatch.invoke(reader.clj:66)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:923)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:905)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:196)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:189)
	at clojure.tools.reader$read_map.invokeStatic(reader.clj:241)
	at clojure.tools.reader$read_map.invoke(reader.clj:237)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:923)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:905)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:196)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:189)
	at clojure.tools.reader$read_vector.invokeStatic(reader.clj:225)
	at clojure.tools.reader$read_vector.invoke(reader.clj:221)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:923)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:905)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:196)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:189)
	at clojure.tools.reader$read_list.invokeStatic(reader.clj:207)
	at clojure.tools.reader$read_list.invoke(reader.clj:203)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:923)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:905)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:196)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:189)
	at clojure.tools.reader$read_list.invokeStatic(reader.clj:207)
	at clojure.tools.reader$read_list.invoke(reader.clj:203)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:923)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:905)
	at clojure.tools.reader$read_delimited.invokeStatic(reader.clj:196)
	at clojure.tools.reader$read_delimited.invoke(reader.clj:189)
	at clojure.tools.reader$read_list.invokeStatic(reader.clj:207)
	at clojure.tools.reader$read_list.invoke(reader.clj:203)
	at clojure.tools.reader$read_STAR_.invokeStatic(reader.clj:923)
	at clojure.tools.reader$read_STAR_.invoke(reader.clj:905)
	at clojure.tools.reader$read.invokeStatic(reader.clj:972)
	at clojure.tools.reader$read.invoke(reader.clj:949)
	at cloverage.instrument$instrument$fn__1847.invoke(instrument.clj:422)
	at cloverage.instrument$instrument.invokeStatic(instrument.clj:421)
	at cloverage.instrument$instrument.invoke(instrument.clj:415)
	at cloverage.coverage$run_main$fn__2953.invoke(coverage.clj:202)
	at cloverage.coverage$run_main.invokeStatic(coverage.clj:199)
	at cloverage.coverage$run_main.invoke(coverage.clj:158)
	at cloverage.coverage$_main.invokeStatic(coverage.clj:256)
	at cloverage.coverage$_main.doInvoke(coverage.clj:251)
	at clojure.lang.RestFn.invoke(RestFn.java:3894)
	at clojure.lang.Var.invoke(Var.java:676)
	at user$eval13.invokeStatic(74780825e58d49516ee72081470407c9461ba94a-init.clj:1)
	at user$eval13.invoke(74780825e58d49516ee72081470407c9461ba94a-init.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6978)
	at clojure.lang.Compiler.eval(Compiler.java:6968)
	at clojure.lang.Compiler.load(Compiler.java:7430)
	... 12 more
Error encountered performing task 'do' with profile(s): 'test'
```

**Comment by lvh** [comment]
#255 may have fixed this. @kenrestivo-stem could you check with a master build and let me know if it's still broken?
