### ISSUE TITLE
Using with core.async 0.3+ causes java.lang.ClassCastException

### ISSUE THREAD

**Issue by cgriego** [cloverage/cloverage#208]
While loading namespaces when using core.async 0.3+, the following error occurs:

```
Exception in thread "main" java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to clojure.lang.Compiler$LocalBinding, compiling:(/private/var/folders/z1/fgcnpwd97gg_yq93hln4k0tw0000gn/T/form-init7520891866768933259.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to clojure.lang.Compiler$LocalBinding
	at clojure.lang.Compiler.referenceLocal(Compiler.java:7139)
	at clojure.lang.Compiler.isMacro(Compiler.java:6567)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:6626)
	at clojure.core$macroexpand_1.invoke(core.clj:3870)
	at clojure.core$macroexpand.invoke(core.clj:3879)
	at cloverage.instrument$eval1361$fn__1362.invoke(instrument.clj:371)
	at clojure.lang.MultiFn.invoke(MultiFn.java:243)
	at cloverage.instrument$wrapm.invoke(instrument.clj:146)
	...
```

core async 0.2 works.

**Comment by TimoFreiberg** [comment]
same with the current master of https://github.com/suprematic/otplike/

**Comment by TimoFreiberg** [comment]
Debug output for the otplike failure:
```
...
Wrapping  clojure.lang.Cons (clojure.lang.Var/resetThreadBindingFrame old-frame__7382__auto__)
java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to clojure.lang.Compiler$LocalBinding
	at clojure.lang.Compiler.referenceLocal(Compiler.java:7289)
	at clojure.lang.Compiler.isMacro(Compiler.java:6712)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:6771)
	at clojure.core$macroexpand_1.invokeStatic(core.clj:3894)
	at clojure.core$macroexpand.invokeStatic(core.clj:3896)
	at clojure.core$macroexpand.invoke(core.clj:3896)
	at cloverage.instrument$eval1421$fn__1422.invoke(instrument.clj:375)
```

The real debug run took too long for my tastes, so I used a locally installed cloverage where I changed the `(tprnl "Wrapping " (class form) form)` at instrument.clj:374 to `(println "Wrapping " (class form) form)` and didn't call it with `--debug`.
Not sure what to make of this, maybe I'll take another look in the next few days.

**Comment by TimoFreiberg** [comment]
Ok.
I used a locally built clojure with a better error message at the cast in `referenceLocal` and found out that `RT.get(LOCAL_ENV.deref(), sym)` returns `:riddley.compiler/analyze-failure`.
So I modified riddley locally to at least print the stack trace at https://github.com/ztellman/riddley/blob/master/src/riddley/compiler.clj#L67, and the exception that get's hidden from me is:
```
java.lang.RuntimeException: Method code too large!, compiling:(/tmp/form-init2997881006784818858.clj:1:146)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6875)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3766)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6870)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$TryExpr$Parser.parse(Compiler.java:2248)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6005)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at riddley.Util.localBinding(Util.java:9)
```

Still not sure where something needs to be fixed ;)

**Comment by Otann** [comment]
Hi @TimoFreiberg,
Did you figure out the solution to this?

**Comment by TimoFreiberg** [comment]
@Otann nope, sorry. In my case, there was an exception in the code that was analyzed (`java.lang.RuntimeException: Method code too large!`), so that needed to be fixed. Riddley doesn't help the usability there by swallowing that exception... but it doesn't look like that's going to be changed :woman_shrugging:
