### ISSUE TITLE
Bug with deftype

### ISSUE THREAD

**Issue by AndreaCrotti** [cloverage/cloverage#257]
Yesterday we had a bit of a surprise when test coverage stopped working.

First because it was working fine on Friday and on the same commit it was failing the Monday after.
This turns out was just because:
- a new version of cloverage came out the 6th of October
- we had pinned the version of "lein-cloverage" but not cloverage the library

This meant that "cloverage" auto updated and we hit a bug with the `deftype*` instrumentation.

So I guess that ideally "lein-cloverage" should pin its own corresponding "cloverage" version to avoid these kind of surprises in the future?

The actual error with version 1.1.2 is attached below.
I can also provide a sample failing form if it's useful, what's the best way to help?

```
Caused by: Syntax error compiling deftype* at _(our_code.clj:1:198)._
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7114)
	at clojure.lang.Compiler.analyze(Compiler.java:6789)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7094)
	at clojure.lang.Compiler.analyze(Compiler.java:6789)
	at clojure.lang.Compiler.analyze(Compiler.java:6745)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6118)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6436)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7106)
	at clojure.lang.Compiler.analyze(Compiler.java:6789)
	at clojure.lang.Compiler.analyze(Compiler.java:6745)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6120)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5467)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4029)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7104)
	at clojure.lang.Compiler.analyze(Compiler.java:6789)
	at clojure.lang.Compiler.eval(Compiler.java:7173)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.eval(Compiler.java:7131)
	at clojure.core$eval.invokeStatic(core.clj:3214)
	at clojure.core$eval.invoke(core.clj:3210)
	at cloverage.instrument$instrument$fn__52271$fn__52272.invoke(instrument.clj:460)
	at cloverage.instrument$instrument$fn__52271.invoke(instrument.clj:458)
	... 25 more
Caused by: java.lang.IllegalArgumentException: Must assign primitive to primitive mutable: __hasheq
```

**Comment by lvh** [comment]
Sorry to hear that!

1. Yes, a reproducer would be great. 
2. cc @camsaul since they contributed the deftype code so they probably have opinions on how it works.

**Comment by AndreaCrotti** [comment]
So the form that makes everything explode with that error above is here below.
There is the `__hasheq` in the arguments as you can see, which is probably related.

I tried to add a test to prove the failure but I didn't manage.
Let me know if you need any more information, thanks

```
(def sample-deftype-form
  '(deftype* finops-admin.db.postgres/enum finops_admin.db.postgres.enum [type value __meta __extmap __hash __hasheq] :implements [clojure.java.jdbc.ISQLValue honeysql.format.ToSql clojure.lang.IRecord clojure.lang.IHashEq clojure.lang.IObj clojure.lang.ILookup clojure.lang.IKeywordLookup clojure.lang.IPersistentMap java.util.Map java.io.Serializable] (clojure.core/entrySet [this__7800__auto__] (do (cloverage.coverage/cover 9417) ((do (cloverage.coverage/cover 9418) clojure.core/set) (do (cloverage.coverage/cover 9419) this__7800__auto__)))) (clojure.core/values [this__7799__auto__] (do (cloverage.coverage/cover 9420) ((do (cloverage.coverage/cover 9421) clojure.core/vals) (do (cloverage.coverage/cover 9422) this__7799__auto__)))) (clojure.core/keySet [this__7798__auto__] (do (cloverage.coverage/cover 9423) ((do (cloverage.coverage/cover 9424) clojure.core/set) (do (cloverage.coverage/cover 9425) ((do (cloverage.coverage/cover 9426) clojure.core/keys) (do (cloverage.coverage/cover 9427) this__7798__auto__)))))) (clojure.core/clear [this__7797__auto__] (do (cloverage.coverage/cover 9428) (throw (do (cloverage.coverage/cover 9429) (new java.lang.UnsupportedOperationException))))) (clojure.core/putAll [this__7795__auto__ m__7796__auto__] (do (cloverage.coverage/cover 9430) (throw (do (cloverage.coverage/cover 9431) (new java.lang.UnsupportedOperationException))))) (clojure.core/remove [this__7793__auto__ k__7794__auto__] (do (cloverage.coverage/cover 9432) (throw (do (cloverage.coverage/cover 9433) (new java.lang.UnsupportedOperationException))))) (clojure.core/put [this__7790__auto__ k__7791__auto__ v__7792__auto__] (do (cloverage.coverage/cover 9434) (throw (do (cloverage.coverage/cover 9435) (new java.lang.UnsupportedOperationException))))) (clojure.core/get [this__7788__auto__ k__7789__auto__] (do (cloverage.coverage/cover 9436) (. this__7788__auto__ valAt (do (cloverage.coverage/cover 9437) k__7789__auto__)))) (clojure.core/containsValue [this__7786__auto__ v__7787__auto__] (do (cloverage.coverage/cover 9438) ((do (cloverage.coverage/cover 9439) clojure.core/boolean) (do (cloverage.coverage/cover 9440) ((do (cloverage.coverage/cover 9441) clojure.core/some) (do (cloverage.coverage/cover 9442) #{(do (cloverage.coverage/cover 9443) v__7787__auto__)}) (do (cloverage.coverage/cover 9444) ((do (cloverage.coverage/cover 9445) clojure.core/vals) (do (cloverage.coverage/cover 9446) this__7786__auto__)))))))) (clojure.core/isEmpty [this__7785__auto__] (do (cloverage.coverage/cover 9447) ((do (cloverage.coverage/cover 9448) clojure.core/=) (do (cloverage.coverage/cover 9449) 0) (do (cloverage.coverage/cover 9450) (. this__7785__auto__ count))))) (clojure.core/size [this__7784__auto__] (do (cloverage.coverage/cover 9451) (. this__7784__auto__ count))) (clojure.core/without [this__7782__auto__ k__7783__auto__] (do (cloverage.coverage/cover 9452) (if (do (cloverage.coverage/cover 9453) ((do (cloverage.coverage/cover 9454) clojure.core/contains?) (do (cloverage.coverage/cover 9455) #{(do (cloverage.coverage/cover 9456) :type) (do (cloverage.coverage/cover 9457) :value)}) (do (cloverage.coverage/cover 9458) k__7783__auto__))) (do (cloverage.coverage/cover 9459) ((do (cloverage.coverage/cover 9460) clojure.core/dissoc) (do (cloverage.coverage/cover 9461) ((do (cloverage.coverage/cover 9462) clojure.core/with-meta) (do (cloverage.coverage/cover 9463) ((do (cloverage.coverage/cover 9464) clojure.core/into) (do (cloverage.coverage/cover 9465) {}) (do (cloverage.coverage/cover 9466) this__7782__auto__))) (do (cloverage.coverage/cover 9467) __meta))) (do (cloverage.coverage/cover 9468) k__7783__auto__))) (do (cloverage.coverage/cover 9469) (new enum (do (cloverage.coverage/cover 9470) type) (do (cloverage.coverage/cover 9471) value) (do (cloverage.coverage/cover 9472) __meta) (do (cloverage.coverage/cover 9473) ((do (cloverage.coverage/cover 9474) clojure.core/not-empty) (do (cloverage.coverage/cover 9475) ((do (cloverage.coverage/cover 9476) clojure.core/dissoc) (do (cloverage.coverage/cover 9477) __extmap) (do (cloverage.coverage/cover 9478) k__7783__auto__)))))))))) (clojure.core/assoc [this__7780__auto__ k__7781__auto__ G__56380] (do (cloverage.coverage/cover 9479) (let* [pred__56381 (do (cloverage.coverage/cover 9480) clojure.core/identical?) expr__56382 (do (cloverage.coverage/cover 9481) k__7781__auto__)] (do (cloverage.coverage/cover 9482) (if (do (cloverage.coverage/cover 9483) ((do (cloverage.coverage/cover 9484) pred__56381) (do (cloverage.coverage/cover 9485) :type) (do (cloverage.coverage/cover 9486) expr__56382))) (do (cloverage.coverage/cover 9487) (new enum (do (cloverage.coverage/cover 9488) G__56380) (do (cloverage.coverage/cover 9489) value) (do (cloverage.coverage/cover 9490) __meta) (do (cloverage.coverage/cover 9491) __extmap))) (do (cloverage.coverage/cover 9492) (if (do (cloverage.coverage/cover 9493) ((do (cloverage.coverage/cover 9494) pred__56381) (do (cloverage.coverage/cover 9495) :value) (do (cloverage.coverage/cover 9496) expr__56382))) (do (cloverage.coverage/cover 9497) (new enum (do (cloverage.coverage/cover 9498) type) (do (cloverage.coverage/cover 9499) G__56380) (do (cloverage.coverage/cover 9500) __meta) (do (cloverage.coverage/cover 9501) __extmap))) (do (cloverage.coverage/cover 9502) (new enum (do (cloverage.coverage/cover 9503) type) (do (cloverage.coverage/cover 9504) value) (do (cloverage.coverage/cover 9505) __meta) (do (cloverage.coverage/cover 9506) ((do (cloverage.coverage/cover 9507) clojure.core/assoc) (do (cloverage.coverage/cover 9508) __extmap) (do (cloverage.coverage/cover 9509) k__7781__auto__) (do (cloverage.coverage/cover 9510) G__56380)))))))))))) (clojure.core/iterator [G__56380] (do (cloverage.coverage/cover 9511) (new clojure.lang.RecordIterator (do (cloverage.coverage/cover 9512) G__56380) (do (cloverage.coverage/cover 9513) [(do (cloverage.coverage/cover 9514) :type) (do (cloverage.coverage/cover 9515) :value)]) (do (cloverage.coverage/cover 9516) (. clojure.lang.RT iter (do (cloverage.coverage/cover 9517) __extmap)))))) (clojure.core/seq [this__7779__auto__] (do (cloverage.coverage/cover 9518) ((do (cloverage.coverage/cover 9519) clojure.core/seq) (do (cloverage.coverage/cover 9520) ((do (cloverage.coverage/cover 9521) clojure.core/concat) (do (cloverage.coverage/cover 9522) [(do (cloverage.coverage/cover 9523) (. clojure.lang.MapEntry create (do (cloverage.coverage/cover 9524) :type) (do (cloverage.coverage/cover 9525) type))) (do (cloverage.coverage/cover 9526) (. clojure.lang.MapEntry create (do (cloverage.coverage/cover 9527) :value) (do (cloverage.coverage/cover 9528) value)))]) (do (cloverage.coverage/cover 9529) __extmap)))))) (clojure.core/entryAt [this__7775__auto__ k__7776__auto__] (do (cloverage.coverage/cover 9530) (let* [v__7777__auto__ (do (cloverage.coverage/cover 9531) (. this__7775__auto__ valAt (do (cloverage.coverage/cover 9532) k__7776__auto__) (do (cloverage.coverage/cover 9533) this__7775__auto__)))] (do (cloverage.coverage/cover 9534) (if (do (cloverage.coverage/cover 9535) ((do (cloverage.coverage/cover 9536) clojure.core/identical?) (do (cloverage.coverage/cover 9537) this__7775__auto__) (do (cloverage.coverage/cover 9538) v__7777__auto__))) (do (cloverage.coverage/cover 9539) nil) (do (cloverage.coverage/cover 9540) (do (do (cloverage.coverage/cover 9541) (. clojure.lang.MapEntry create (do (cloverage.coverage/cover 9542) k__7776__auto__) (do (cloverage.coverage/cover 9543) v__7777__auto__)))))))))) (clojure.core/containsKey [this__7773__auto__ k__7774__auto__] (do (cloverage.coverage/cover 9544) ((do (cloverage.coverage/cover 9545) clojure.core/not) (do (cloverage.coverage/cover 9546) ((do (cloverage.coverage/cover 9547) clojure.core/identical?) (do (cloverage.coverage/cover 9548) this__7773__auto__) (do (cloverage.coverage/cover 9549) (. this__7773__auto__ valAt (do (cloverage.coverage/cover 9550) k__7774__auto__) (do (cloverage.coverage/cover 9551) this__7773__auto__)))))))) (clojure.core/equiv [this__7772__auto__ G__56380] (do (cloverage.coverage/cover 9552) ((do (cloverage.coverage/cover 9553) clojure.core/boolean) (do (cloverage.coverage/cover 9554) (let* [or__5501__auto__ (do (cloverage.coverage/cover 9555) ((do (cloverage.coverage/cover 9556) clojure.core/identical?) (do (cloverage.coverage/cover 9557) this__7772__auto__) (do (cloverage.coverage/cover 9558) G__56380)))] (do (cloverage.coverage/cover 9559) (if (do (cloverage.coverage/cover 9560) or__5501__auto__) (do (cloverage.coverage/cover 9561) or__5501__auto__) (do (cloverage.coverage/cover 9562) (if (do (cloverage.coverage/cover 9563) ((do (cloverage.coverage/cover 9564) clojure.core/identical?) (do (cloverage.coverage/cover 9565) ((do (cloverage.coverage/cover 9566) clojure.core/class) (do (cloverage.coverage/cover 9567) this__7772__auto__))) (do (cloverage.coverage/cover 9568) ((do (cloverage.coverage/cover 9569) clojure.core/class) (do (cloverage.coverage/cover 9570) G__56380))))) (do (cloverage.coverage/cover 9571) (do (do (cloverage.coverage/cover 9572) (let* [G__56380 (do (cloverage.coverage/cover 9573) G__56380)] (do (cloverage.coverage/cover 9574) (let* [and__5499__auto__ (do (cloverage.coverage/cover 9575) ((do (cloverage.coverage/cover 9576) clojure.core/=) (do (cloverage.coverage/cover 9577) type) (do (cloverage.coverage/cover 9578) (. G__56380 -type))))] (do (cloverage.coverage/cover 9579) (if (do (cloverage.coverage/cover 9580) and__5499__auto__) (do (cloverage.coverage/cover 9581) (let* [and__5499__auto__ (do (cloverage.coverage/cover 9582) ((do (cloverage.coverage/cover 9583) clojure.core/=) (do (cloverage.coverage/cover 9584) value) (do (cloverage.coverage/cover 9585) (. G__56380 -value))))] (do (cloverage.coverage/cover 9586) (if (do (cloverage.coverage/cover 9587) and__5499__auto__) (do (cloverage.coverage/cover 9588) ((do (cloverage.coverage/cover 9589) clojure.core/=) (do (cloverage.coverage/cover 9590) __extmap) (do (cloverage.coverage/cover 9591) (. G__56380 __extmap)))) (do (cloverage.coverage/cover 9592) and__5499__auto__))))) (do (cloverage.coverage/cover 9593) and__5499__auto__)))))))))))))))))) (clojure.core/cons [this__7770__auto__ e__7771__auto__] (do (cloverage.coverage/cover 9594) ((do (cloverage.coverage/cover 9595) (var clojure.core/imap-cons)) (do (cloverage.coverage/cover 9596) this__7770__auto__) (do (cloverage.coverage/cover 9597) e__7771__auto__)))) (clojure.core/empty [this__7769__auto__] (do (cloverage.coverage/cover 9598) (throw (do (cloverage.coverage/cover 9599) (new java.lang.UnsupportedOperationException (do (cloverage.coverage/cover 9600) ((do (cloverage.coverage/cover 9601) clojure.core/str) (do (cloverage.coverage/cover 9602) "Can't create empty: ") (do (cloverage.coverage/cover 9603) "finops_admin.db.postgres.enum")))))))) (clojure.core/count [this__7768__auto__] (do (cloverage.coverage/cover 9604) ((do (cloverage.coverage/cover 9605) clojure.core/+) (do (cloverage.coverage/cover 9606) 2) (do (cloverage.coverage/cover 9607) ((do (cloverage.coverage/cover 9608) clojure.core/count) (do (cloverage.coverage/cover 9609) __extmap)))))) (clojure.core/getLookupThunk [this__7766__auto__ k__7767__auto__] (do (cloverage.coverage/cover 9610) (let* [gclass (do (cloverage.coverage/cover 9611) ((do (cloverage.coverage/cover 9612) clojure.core/class) (do (cloverage.coverage/cover 9613) this__7766__auto__)))] (do (cloverage.coverage/cover 9614) (let* [G__56383 (do (cloverage.coverage/cover 9615) k__7767__auto__)] (do (cloverage.coverage/cover 9616) (case* G__56383 0 1 (do (cloverage.coverage/cover 9617) nil) {0 [:type (do (cloverage.coverage/cover 9618) (reify* [clojure.lang.ILookupThunk] (clojure.core/get [thunk gtarget] (do (cloverage.coverage/cover 9619) (if (do (cloverage.coverage/cover 9620) ((do (cloverage.coverage/cover 9621) clojure.core/identical?) (do (cloverage.coverage/cover 9622) ((do (cloverage.coverage/cover 9623) clojure.core/class) (do (cloverage.coverage/cover 9624) gtarget))) (do (cloverage.coverage/cover 9625) gclass))) (do (cloverage.coverage/cover 9626) (. gtarget -type)) (do (cloverage.coverage/cover 9627) thunk))))))], 1 [:value (do (cloverage.coverage/cover 9628) (reify* [clojure.lang.ILookupThunk] (clojure.core/get [thunk gtarget] (do (cloverage.coverage/cover 9629) (if (do (cloverage.coverage/cover 9630) ((do (cloverage.coverage/cover 9631) clojure.core/identical?) (do (cloverage.coverage/cover 9632) ((do (cloverage.coverage/cover 9633) clojure.core/class) (do (cloverage.coverage/cover 9634) gtarget))) (do (cloverage.coverage/cover 9635) gclass))) (do (cloverage.coverage/cover 9636) (. gtarget -value)) (do (cloverage.coverage/cover 9637) thunk))))))]} :compact :hash-identity nil))))))) (clojure.core/valAt [this__7763__auto__ k__7764__auto__ else__7765__auto__] (do (cloverage.coverage/cover 9638) (let* [G__56384 (do (cloverage.coverage/cover 9639) k__7764__auto__)] (do (cloverage.coverage/cover 9640) (case* G__56384 0 1 (do (cloverage.coverage/cover 9641) ((do (cloverage.coverage/cover 9642) clojure.core/get) (do (cloverage.coverage/cover 9643) __extmap) (do (cloverage.coverage/cover 9644) k__7764__auto__) (do (cloverage.coverage/cover 9645) else__7765__auto__))) {0 [:type (do (cloverage.coverage/cover 9646) type)], 1 [:value (do (cloverage.coverage/cover 9647) value)]} :compact :hash-identity nil))))) (clojure.core/valAt [this__7761__auto__ k__7762__auto__] (do (cloverage.coverage/cover 9648) (. this__7761__auto__ valAt (do (cloverage.coverage/cover 9649) k__7762__auto__) (do (cloverage.coverage/cover 9650) nil)))) (clojure.core/withMeta [this__7760__auto__ G__56380] (do (cloverage.coverage/cover 9651) (new enum (do (cloverage.coverage/cover 9652) type) (do (cloverage.coverage/cover 9653) value) (do (cloverage.coverage/cover 9654) G__56380) (do (cloverage.coverage/cover 9655) __extmap) (do (cloverage.coverage/cover 9656) __hash) (do (cloverage.coverage/cover 9657) __hasheq)))) (clojure.core/meta [this__7759__auto__] (do (cloverage.coverage/cover 9658) __meta)) (clojure.core/equals [this__7758__auto__ G__56380] (do (cloverage.coverage/cover 9659) (. clojure.lang.APersistentMap mapEquals (do (cloverage.coverage/cover 9660) this__7758__auto__) (do (cloverage.coverage/cover 9661) G__56380)))) (clojure.core/hashCode [this__7755__auto__] (do (cloverage.coverage/cover 9662) (let* [hash__7756__auto__ (do (cloverage.coverage/cover 9663) __hash)] (do (cloverage.coverage/cover 9664) (if (do (cloverage.coverage/cover 9665) ((do (cloverage.coverage/cover 9666) clojure.core/zero?) (do (cloverage.coverage/cover 9667) hash__7756__auto__))) (do (cloverage.coverage/cover 9668) (let* [h__7757__auto__ (do (cloverage.coverage/cover 9669) (. clojure.lang.APersistentMap mapHash (do (cloverage.coverage/cover 9670) this__7755__auto__)))] (do (cloverage.coverage/cover 9671) (set! __hash (do (cloverage.coverage/cover 9672) h__7757__auto__))) (do (cloverage.coverage/cover 9673) h__7757__auto__))) (do (cloverage.coverage/cover 9674) hash__7756__auto__)))))) (clojure.core/hasheq [this__7752__auto__] (do (cloverage.coverage/cover 9675) (let* [hq__7753__auto__ (do (cloverage.coverage/cover 9676) __hasheq)] (do (cloverage.coverage/cover 9677) (if (do (cloverage.coverage/cover 9678) ((do (cloverage.coverage/cover 9679) clojure.core/zero?) (do (cloverage.coverage/cover 9680) hq__7753__auto__))) (do (cloverage.coverage/cover 9681) (let* [h__7754__auto__ (do (cloverage.coverage/cover 9682) ((do (cloverage.coverage/cover 9683) clojure.core/int) (do (cloverage.coverage/cover 9684) ((do (cloverage.coverage/cover 9685) clojure.core/bit-xor) (do (cloverage.coverage/cover 9686) -1580735653) (do (cloverage.coverage/cover 9687) (. clojure.lang.APersistentMap mapHasheq (do (cloverage.coverage/cover 9688) this__7752__auto__)))))))] (do (cloverage.coverage/cover 9689) (set! __hasheq (do (cloverage.coverage/cover 9690) h__7754__auto__))) (do (cloverage.coverage/cover 9691) h__7754__auto__))) (do (cloverage.coverage/cover 9692) hq__7753__auto__)))))) (finops-admin.db.postgres/sql-value [this] (do (cloverage.coverage/cover 9693) ((do (cloverage.coverage/cover 9694) ->pg-object) (do (cloverage.coverage/cover 9695) type) (do (cloverage.coverage/cover 9696) value)))) (finops-admin.db.postgres/to-sql [this] (do (cloverage.coverage/cover 9697) ((do (cloverage.coverage/cover 9698) honeysql.format/add-anon-param) (do (cloverage.coverage/cover 9699) this))))))```

**Comment by nwjsmith** [comment]
@AndreaCrotti Could you provide the original, non-macroexpanded source for the `(hasheq [this])` method? I'm trying to put together a test to reproduce this, and that would be a great help.

**Comment by AndreaCrotti** [comment]
I extracted some code which I think causes this here
https://github.com/AndreaCrotti/cloverage-issue

interestingly I get a different error there but it still fails.

**Comment by AndreaCrotti** [comment]
So if you need more help let me know @nwjsmith , it's somehow related with the pgobject and postgresql/jdbc magic, we don't really write any of that code causing the failures ourselves.

**Comment by camsaul** [comment]
So there are actually a few problems here.

1.  Normally `defrecord` is instrumented before fully expanded into a `deftype*` form, which contains a dozen or so method implementations for Clojure methods. The methods that get generated normally don't get instrumented, which makes sense -- we shouldn't care if you never invoke one of the map equality methods generated by `defrecord` in your code. However, for unknown forms, including macros like Potemkin `deftype+` that generate `defrecord` forms, we end up fully macroexpanding the form before attempting to instrument it. Instead, we should attempt to instrument after each macroexpansion.

2.  We instrument inlined primitive forms like `int`. `defrecord` ultimiately generates a method that is something like this:

    ```clj
    (deftype MyType [^:unsynchronized-mutable ^int i]
      clojure.lang.IHashEq
      (hasheq [_]
        (set! i (int 2))))
    ```

    Attemtping to instrument this causes the "Must assign primitive" error:

    ```clj
    (defn instrument [form]
      (inst/instrument-form #'inst/no-instr nil form))
    
    (deftype MyType [^:unsynchronized-mutable ^int i]
      clojure.lang.IHashEq
      (hasheq [_]
        (set! i (instrument (int 2)))))
    ;; -> Must assign primitive to primitive mutable: i
    ```

    I think the correct fix here is not to instrument primitive inline initializers like `int` at all.

3.  It would make sense to fail gracefully when we can't instrument a certain form, rather than having Cloverage fail completely. We can log the exception and proceed normally.
