### ISSUE TITLE
Unexpected error macroexpanding cloverage.instrument/wrapm in Potemkin defrecord+ form

### ISSUE THREAD

**Issue by camsaul** [cloverage/cloverage#271]
A minimal `defrecord+` form will cause Cloverage to fail entirely:

```
(ns cloverage-debugging.core
  (:require [potemkin.types :as p.types]))

(p.types/defrecord+ VinylRecord [])

(defn record-name [m]
  (:name m))

(defn record-with-name [nme]
  (map->VinylRecord {:name nme}))
```

```
Loading namespaces:  (cloverage-debugging.core)
Test namespaces:  (cloverage-debugging.core-test)
Unexpected error macroexpanding cloverage.instrument/wrapm at (/tmp/form-init10181839849700298270.clj:1:147).
        at clojure.lang.Compiler.macroexpand1(Compiler.java:7019)
        at clojure.core$macroexpand_1.invokeStatic(core.clj:4024)
        at clojure.core$macroexpand_1.invoke(core.clj:4018)
        at riddley.walk$macroexpand$fn__1209.invoke(walk.clj:24)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at riddley.walk$macroexpand.invokeStatic(walk.clj:13)
        at riddley.walk$macroexpand.invoke(walk.clj:6)
        at riddley.walk$walk_exprs$fn__1331$fn__1332.invoke(walk.clj:192)
        at riddley.walk$walk_exprs$fn__1331.invoke(walk.clj:191)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at riddley.walk$walk_exprs.invokeStatic(walk.clj:190)
        at riddley.walk$walk_exprs.invoke(walk.clj:175)
        at clojure.core$partial$fn__5843.invoke(core.clj:2638)
        at clojure.core$map$fn__5866.invoke(core.clj:2755)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:713)
        at clojure.core$next__5386.invokeStatic(core.clj:64)
        at clojure.core$dorun.invokeStatic(core.clj:3142)
        at clojure.core$doall.invokeStatic(core.clj:3148)
        at clojure.core$doall.invoke(core.clj:3148)
        at riddley.walk$fn_handler$body_handler__1226$fn__1227.invoke(walk.clj:72)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at riddley.walk$fn_handler$body_handler__1226.invoke(walk.clj:69)
        at clojure.core$map$fn__5866.invoke(core.clj:2755)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5402.invokeStatic(core.clj:137)
        at clojure.core$dorun.invokeStatic(core.clj:3133)
        at clojure.core$doall.invokeStatic(core.clj:3148)
        at clojure.core$doall.invoke(core.clj:3148)
        at riddley.walk$fn_handler$fn__1236.invoke(walk.clj:87)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at riddley.walk$fn_handler.invokeStatic(walk.clj:76)
        at riddley.walk$fn_handler.invoke(walk.clj:63)
        at riddley.walk$walk_exprs$fn__1331.invoke(walk.clj:208)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at riddley.walk$walk_exprs.invokeStatic(walk.clj:190)
        at riddley.walk$walk_exprs.invoke(walk.clj:175)
        at clojure.core$partial$fn__5843.invoke(core.clj:2638)
        at clojure.core$map$fn__5866.invoke(core.clj:2755)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5402.invokeStatic(core.clj:137)
        at clojure.core$dorun.invokeStatic(core.clj:3133)
        at clojure.core$doall.invokeStatic(core.clj:3148)
        at clojure.core$doall.invoke(core.clj:3148)
        at riddley.walk$def_handler$fn__1245.invoke(walk.clj:94)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at riddley.walk$def_handler.invokeStatic(walk.clj:92)
        at riddley.walk$def_handler.invoke(walk.clj:90)
        at riddley.walk$walk_exprs$fn__1331.invoke(walk.clj:208)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at riddley.walk$walk_exprs.invokeStatic(walk.clj:190)
        at riddley.walk$walk_exprs.invoke(walk.clj:175)
        at clojure.core$partial$fn__5843.invoke(core.clj:2638)
        at clojure.core$map$fn__5866.invoke(core.clj:2755)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:713)
        at clojure.core$next__5386.invokeStatic(core.clj:64)
        at clojure.core$dorun.invokeStatic(core.clj:3142)
        at clojure.core$doall.invokeStatic(core.clj:3148)
        at clojure.core$doall.invoke(core.clj:3148)
        at riddley.walk$do_handler.invokeStatic(walk.clj:60)
        at riddley.walk$do_handler.invoke(walk.clj:58)
        at riddley.walk$walk_exprs$fn__1331.invoke(walk.clj:208)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at riddley.walk$walk_exprs.invokeStatic(walk.clj:190)
        at riddley.walk$walk_exprs.invoke(walk.clj:175)
        at clojure.core$partial$fn__5843.invoke(core.clj:2638)
        at clojure.core$map$fn__5866.invoke(core.clj:2755)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:713)
        at clojure.core$next__5386.invokeStatic(core.clj:64)
        at clojure.core$dorun.invokeStatic(core.clj:3142)
        at clojure.core$doall.invokeStatic(core.clj:3148)
        at clojure.core$doall.invoke(core.clj:3148)
        at riddley.walk$let_handler$fn__1302.invoke(walk.clj:135)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at riddley.walk$let_handler.invokeStatic(walk.clj:134)
        at riddley.walk$let_handler.invoke(walk.clj:133)
        at riddley.walk$walk_exprs$fn__1331.invoke(walk.clj:208)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at riddley.walk$walk_exprs.invokeStatic(walk.clj:190)
        at riddley.walk$walk_exprs.invoke(walk.clj:175)
        at clojure.core$partial$fn__5843.invoke(core.clj:2638)
        at clojure.core$map$fn__5866.invoke(core.clj:2755)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:713)
        at clojure.core$next__5386.invokeStatic(core.clj:64)
        at clojure.core$dorun.invokeStatic(core.clj:3142)
        at clojure.core$doall.invokeStatic(core.clj:3148)
        at clojure.core$doall.invoke(core.clj:3148)
        at riddley.walk$do_handler.invokeStatic(walk.clj:60)
        at riddley.walk$do_handler.invoke(walk.clj:58)
        at riddley.walk$walk_exprs$fn__1331.invoke(walk.clj:208)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at riddley.walk$walk_exprs.invokeStatic(walk.clj:190)
        at riddley.walk$walk_exprs.invoke(walk.clj:175)
        at riddley.walk$walk_exprs.invokeStatic(walk.clj:188)
        at riddley.walk$walk_exprs.invoke(walk.clj:175)
        at riddley.walk$macroexpand_all.invokeStatic(walk.clj:254)
        at riddley.walk$macroexpand_all.invoke(walk.clj:251)
        at cloverage.instrument$instrument$fn__1808$fn__1814.invoke(instrument.clj:468)
        at cloverage.instrument$instrument$fn__1808.invoke(instrument.clj:468)
        at cloverage.instrument$instrument.invokeStatic(instrument.clj:457)
        at cloverage.instrument$instrument.invoke(instrument.clj:436)
        at cloverage.coverage$run_main$fn__2931.invoke(coverage.clj:238)
        at cloverage.coverage$run_main.invokeStatic(coverage.clj:233)
        at cloverage.coverage$run_main.invoke(coverage.clj:183)
        at cloverage.coverage$run_project.invokeStatic(coverage.clj:290)
        at cloverage.coverage$run_project.doInvoke(coverage.clj:286)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at user$eval2943.invokeStatic(form-init10181839849700298270.clj:1)
        at user$eval2943.invoke(form-init10181839849700298270.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7177)
        at clojure.lang.Compiler.eval(Compiler.java:7167)
        at clojure.lang.Compiler.load(Compiler.java:7636)
        at clojure.lang.Compiler.loadFile(Compiler.java:7574)
        at clojure.main$load_script.invokeStatic(main.clj:475)
        at clojure.main$init_opt.invokeStatic(main.clj:477)
        at clojure.main$init_opt.invoke(main.clj:477)
        at clojure.main$initialize.invokeStatic(main.clj:508)
        at clojure.main$null_opt.invokeStatic(main.clj:542)
        at clojure.main$null_opt.invoke(main.clj:539)
        at clojure.main$main.invokeStatic(main.clj:664)
        at clojure.main$main.doInvoke(main.clj:616)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:40)
Caused by: java.lang.ClassNotFoundException: cloverage_debugging.core.VinylRecord
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
        at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:427)
        at clojure.lang.RT.classForName(RT.java:2211)
        at clojure.lang.RT.classForNameNonLoading(RT.java:2224)
        at clojure.lang.Compiler$HostExpr.maybeClass(Compiler.java:1041)
        at clojure.lang.Compiler.macroexpand1(Compiler.java:7045)
        at clojure.core$macroexpand_1.invokeStatic(core.clj:4024)
        at clojure.core$macroexpand.invokeStatic(core.clj:4026)
        at clojure.core$macroexpand.invoke(core.clj:4026)
        at cloverage.instrument$eval1715$fn__1716.invoke(instrument.clj:380)
        at clojure.lang.MultiFn.invoke(MultiFn.java:244)
        at cloverage.instrument$wrapm.invokeStatic(instrument.clj:144)
        at cloverage.instrument$wrapm.invoke(instrument.clj:138)
        at clojure.lang.AFn.applyToHelper(AFn.java:171)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.lang.Compiler.macroexpand1(Compiler.java:6993)
        ... 193 more
Unexpected error (ClassNotFoundException) macroexpanding cloverage.instrument/wrapm at (/tmp/form-init10181839849700298270.clj:1:147).
cloverage_debugging.core.VinylRecord
```
I've created a minimum Leiningen project for reproducing this bug here: https://github.com/camsaul/cloverage-bug-minimal-project.

Attempting to macroexpand that form with Riddley outside of Cloverage works without issue so something else must be going on. I have a bit of experience with the code in question from implementing #254 so I'll try to poke around and see if I can come up with a fix for this issue

Related issue: #47

**Comment by camsaul** [comment]
So this actually looks like the same underlying issue as #257

**Comment by camsaul** [comment]
Duplicate of #257

**Comment by julienba** [comment]
Hello @camsaul,
I just want to say thank you. I was trying to use cloverage on a project with https://github.com/metabase/toucan and I encounter the same error, with your fix, it works.
