### ISSUE TITLE
clojure.lang.Keyword cannot be cast to clojure.lang.Compiler$LocalBinding

### ISSUE THREAD

**Issue by sudharsh** [cloverage/cloverage#293]
Getting the following stacktrace while running `lein cloverage`. 

```WARNING: reader-conditional already refers to: #'clojure.core/reader-conditional in namespace: clojure.tools.reader.impl.utils, being replaced by: #'clojure.tools.reader.impl.utils/reader-conditional
WARNING: tagged-literal already refers to: #'clojure.core/tagged-literal in namespace: clojure.tools.reader.impl.utils, being replaced by: #'clojure.tools.reader.impl.utils/tagged-literal
java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to clojure.lang.Compiler$LocalBinding
        at clojure.lang.Compiler.referenceLocal(Compiler.java:7289)
        at clojure.lang.Compiler.isMacro(Compiler.java:6712)
        at clojure.lang.Compiler.macroexpand1(Compiler.java:6771)
        at clojure.core$macroexpand_1.invokeStatic(core.clj:3894)
        at clojure.core$macroexpand.invokeStatic(core.clj:3896)
        at clojure.core$macroexpand.invoke(core.clj:3896)
        at cloverage.instrument$eval1173$fn__1174.invoke(instrument.clj:380)
        at clojure.lang.MultiFn.invoke(MultiFn.java:243)
        at cloverage.instrument$wrapm.invokeStatic(instrument.clj:144)
        at cloverage.instrument$wrapm.invoke(instrument.clj:138)
        at clojure.lang.Var.invoke(Var.java:401)
        at clojure.lang.AFn.applyToHelper(AFn.java:171)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.lang.Compiler.macroexpand1(Compiler.java:6776)
        at clojure.core$macroexpand_1.invokeStatic(core.clj:3894)
        at clojure.core$macroexpand_1.invoke(core.clj:3888)
        at riddley.walk$macroexpand$fn__879.invoke(walk.clj:24)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at riddley.walk$macroexpand.invokeStatic(walk.clj:13)
        at riddley.walk$macroexpand.invoke(walk.clj:6)
        at riddley.walk$walk_exprs$fn__975$fn__976.invoke(walk.clj:192)
        at riddley.walk$walk_exprs$fn__975.invoke(walk.clj:191)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at riddley.walk$walk_exprs.invokeStatic(walk.clj:190)
        at riddley.walk$walk_exprs.invoke(walk.clj:175)
        at clojure.core$partial$fn__4763.invoke(core.clj:2529)
        at clojure.core$map$fn__4785.invoke(core.clj:2646)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:688)
        at clojure.core$next__4341.invokeStatic(core.clj:64)
        at clojure.core$dorun.invokeStatic(core.clj:3033)
        at clojure.core$doall.invokeStatic(core.clj:3039)
        at clojure.core$doall.invoke(core.clj:3039)
        at riddley.walk$walk_exprs$fn__975$fn__980.invoke(walk.clj:220)
        at riddley.walk$walk_exprs$fn__975.invoke(walk.clj:208)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at riddley.walk$walk_exprs.invokeStatic(walk.clj:190)
        at riddley.walk$walk_exprs.invoke(walk.clj:175)
        at clojure.core$partial$fn__4763.invoke(core.clj:2529)
        at clojure.core$map$fn__4785.invoke(core.clj:2646)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:688)
        ...
        ...
```

Any pointers, much appreciated.

**Comment by vemv** [comment]
Probably an accompanying bug repro would increase the likelihood of getting the issue fixed

Cheers - V

**Comment by lvh** [comment]
Closed because no effective reproducer exists.
