### ISSUE TITLE
java.lang.RuntimeException: No namespaces selected for instrumentation using {:ns-regex (), :ns-exclude-regex ()}

### ISSUE THREAD

**Issue by dknesek** [cloverage/cloverage#312]
I just tried to install and run cloverage on a new project for the first time. I'm in an IntelliJ project directory with these contents:
```
Dougs-MacBook-Pro-2:clj-unit-conversion-grading doug$ ls
CHANGELOG.md			resources
LICENSE				run.sh
README.md			src
clj-unit-conversion-grading.iml	target
doc				test
project.clj
```
Here are the contents of `project.clj`
```
Dougs-MacBook-Pro-2:clj-unit-conversion-grading doug$ cat project.clj 
(defproject clj-unit-conversion-grading "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.1"]]
  :plugins [[lein-cloverage "1.1.2"]]
  :repl-options {:init-ns clj-unit-conversion-grading.core}
  :main grading.core)
```
The src directory contains `core.clj` and the test directory contains `core-test.clj` and a passing `clojure.test` test.
```
Dougs-MacBook-Pro-2:clj-unit-conversion-grading doug$ lein test

lein test core-test
Hello, World!

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.
```
Here's what I ran and the results.
```
Dougs-MacBook-Pro-2:clj-unit-conversion-grading doug$ lein cloverage
java.lang.RuntimeException: No namespaces selected for instrumentation using {:ns-regex (), :ns-exclude-regex ()}
	at cloverage.coverage$load_namespaces.invokeStatic(coverage.clj:160)
	at cloverage.coverage$load_namespaces.invoke(coverage.clj:144)
	at cloverage.coverage$run_main.invokeStatic(coverage.clj:278)
	at cloverage.coverage$run_main.invoke(coverage.clj:272)
	at cloverage.coverage$run_project.invokeStatic(coverage.clj:296)
	at cloverage.coverage$run_project.doInvoke(coverage.clj:292)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at user$eval4169.invokeStatic(form-init6292047107413325575.clj:1)
	at user$eval4169.invoke(form-init6292047107413325575.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7177)
	at clojure.lang.Compiler.eval(Compiler.java:7167)
	at clojure.lang.Compiler.load(Compiler.java:7636)
	at clojure.lang.Compiler.loadFile(Compiler.java:7574)
	at clojure.main$load_script.invokeStatic(main.clj:475)
	at clojure.main$init_opt.invokeStatic(main.clj:477)
	at clojure.main$init_opt.invoke(main.clj:477)
	at clojure.main$initialize.invokeStatic(main.clj:508)
	at clojure.main$null_opt.invokeStatic(main.clj:542)
	at clojure.main$null_opt.invoke(main.clj:539)
	at clojure.main$main.invokeStatic(main.clj:664)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)
Syntax error compiling at (/private/var/folders/76/292grfnd10x7g67vkz57qdww0000gn/T/form-init6292047107413325575.clj:1:125).
No namespaces selected for instrumentation using {:ns-regex (), :ns-exclude-regex ()}

Full report at:
/var/folders/76/292grfnd10x7g67vkz57qdww0000gn/T/clojure-15090757724497152200.edn
```

**Comment by dylangleason** [comment]
I can also reproduce, and it seems to affect all versions going back to `1.1.0` for me. Here is my `project.clj` file:
```clojure
(defproject playground "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.10.1"]]
  :description "FIXME: write description"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :main playground.core
  :plugins [[:lein-cloverage "1.1.0"]]
  :repl-options {:init-ns playground.core}
  :url "http://example.com/FIXME")
```
Here is my project directory:
```
> tree .               
.
├── CHANGELOG.md
├── conf
├── doc
│   └── intro.md
├── LICENSE
├── project.clj
├── README.md
├── resources
├── src
│   └── playground
│       └── core.clj
├── target
│   ├── classes
│   │   └── META-INF
│   │       └── maven
│   │           └── playground
│   │               └── playground
│   │                   └── pom.properties
│   └── stale
│       └── leiningen.core.classpath.extract-native-dependencies
└── test
    └── playground
        └── core_test.clj

14 directories, 9 files
```
Trace:
```
  [[cloverage.coverage$load_namespaces invokeStatic "coverage.clj" 160]
   [cloverage.coverage$load_namespaces invoke "coverage.clj" 144]
   [cloverage.coverage$run_main invokeStatic "coverage.clj" 278]
   [cloverage.coverage$run_main invoke "coverage.clj" 272]
   [cloverage.coverage$run_project invokeStatic "coverage.clj" 296]
   [cloverage.coverage$run_project doInvoke "coverage.clj" 292]
   [clojure.lang.RestFn invoke "RestFn.java" 410]
   [user$eval4169 invokeStatic "form-init8453455377891701311.clj" 1]                                                                                                
   [user$eval4169 invoke "form-init8453455377891701311.clj" 1]
   [clojure.lang.Compiler eval "Compiler.java" 7177]
   [clojure.lang.Compiler eval "Compiler.java" 7167]
   [clojure.lang.Compiler load "Compiler.java" 7636]
   [clojure.lang.Compiler loadFile "Compiler.java" 7574]   
   [clojure.main$load_script invokeStatic "main.clj" 475]     
   [clojure.main$init_opt invokeStatic "main.clj" 477]
   [clojure.main$init_opt invoke "main.clj" 477]
   [clojure.main$initialize invokeStatic "main.clj" 508]                                   
   [clojure.main$null_opt invokeStatic "main.clj" 542]
   [clojure.main$null_opt invoke "main.clj" 539]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]                            
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]]
```
Not sure if it matters, but here is the `leiningen` and OS information:
```
> lein version
Leiningen 2.9.4 on Java 11.0.6 OpenJDK 64-Bit Server VM
```
```
> uname -rv
4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26)
```

**Comment by dylangleason** [comment]
I can report that reverting to version `1.0.9` resolves the issue for me.

**Comment by alexanderkiel** [comment]
I have the same problem with version 1.2.1. The problem is the dependency ordering. I had only one namespace in my project that didn't require anything. Requiring something like clojure.core did solve the problem for me.

**Comment by MokkeMeguru** [comment]
I think this issue is not resolved  in cloverage 1.2.2 .
can you see this repo?
https://github.com/MokkeMeguru/cloverage-experiments
@lvh

**Comment by eu400000** [comment]
Hi, I still have this issue in 1.2.2, should this issue not be re-opened (not sure if that is how things work in GitHub)?

**Comment by lvh** [comment]
@eu400000 Can you please check if the issue is resolved in -SNAPSHOT or git master?

**Comment by eu400000** [comment]
@lvh , I'm sorry, I'm relatively new to Clojure and GitHub. I'm willing to help but need some guidance.
When you mention -SNAPSHOT, I can only see old versions with -SNAPSHOT in Clojar, or should I look somewhere else for 1.2.2-SNAPSHOT (or higher)?
Wrt git master, I can clone the repo to local but then I don't know what to do as there seems to be 2 projects (cloverage and lein-cloverage) and with my limited knowledge of the Clojure eco-system I'm not sure what to do so if you want me to explore this further I respectfully ask for some more guidance.
Regards, Eric

**Comment by vemv** [comment]
The workaround is no longer needed as of Cloverage 1.2.3
