### ISSUE TITLE
lein-cloverage 1.2.2 throws RuntimeException: No namespaces selected for instrumentation using {:ns-regex (), :ns-exclude-regex ()} 

### ISSUE THREAD

**Issue by lowecg** [cloverage/cloverage#318]
I'm attempting a basic cloverage run and I'm getting an RTE:

```
$ lein version
Leiningen 2.9.5 on Java 11.0.9 OpenJDK 64-Bit Server VM
$ lein new demo
cd demo/
(edit project.clj to add plugin)
$ cat project.clj
(defproject demo "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.1"]]
  :repl-options {:init-ns demo.core}
  :plugins [[lein-cloverage "1.2.2"]]
)
$ lein cloverage
java.lang.RuntimeException: No namespaces selected for instrumentation using {:ns-regex (), :ns-exclude-regex ()}
	at cloverage.coverage$load_namespaces.invokeStatic(coverage.clj:160)
	at cloverage.coverage$load_namespaces.invoke(coverage.clj:144)
	at cloverage.coverage$run_main.invokeStatic(coverage.clj:305)
	at cloverage.coverage$run_main.invoke(coverage.clj:299)
	at cloverage.coverage$run_project.invokeStatic(coverage.clj:323)
	at cloverage.coverage$run_project.doInvoke(coverage.clj:319)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at user$eval4262.invokeStatic(form-init6874990716670776120.clj:1)
	at user$eval4262.invoke(form-init6874990716670776120.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7177)
	at clojure.lang.Compiler.eval(Compiler.java:7167)
        at clojure.lang.Compiler.load(Compiler.java:7636)
	at clojure.lang.Compiler.loadFile(Compiler.java:7574)
	at clojure.main$load_script.invokeStatic(main.clj:475)
	at clojure.main$init_opt.invokeStatic(main.clj:477)
	at clojure.main$init_opt.invoke(main.clj:477)
	at clojure.main$initialize.invokeStatic(main.clj:508)
	at clojure.main$null_opt.invokeStatic(main.clj:542)
	at clojure.main$null_opt.invoke(main.clj:539)
	at clojure.main$main.invokeStatic(main.clj:664)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)
Syntax error compiling at (/private/var/folders/kb/z7kbym91377dd_vwldhdnzl80000gn/T/form-init6874990716670776120.clj:1:125).
No namespaces selected for instrumentation using {:ns-regex (), :ns-exclude-regex ()}

Full report at:
/var/folders/kb/z7kbym91377dd_vwldhdnzl80000gn/T/clojure-217655934742070685.edn
```
Report attached:

[clojure-217655934742070685.edn.zip](https://github.com/cloverage/cloverage/files/6070678/clojure-217655934742070685.edn.zip)

Any ideas on what's wrong here?

**Comment by extesy** [comment]
I have the same problem after upgrading lein-cloverage to 1.2.2, could be seen in automated travis-ci test run: https://travis-ci.org/github/extesy/99-problems/builds/762081819

**Comment by MokkeMeguru** [comment]
I have same problem in 1.2.2
ref: https://github.com/cloverage/cloverage/issues/312
I think you can add `(:require [clojure.core])` in your isolated namespace like

```clojure
(ns demo.core
  (:require [clojure.core]) ;; need here code!!!
  )

(defn foo
  "I don't do a whole lot."
  [x]
  (println x "Hello, World!"))

(defn main []
  (print "hello"))

```

**Comment by lowecg** [comment]
@MokkeMeguru thank you - that indeed got things working for me.

**Comment by vemv** [comment]
The workaround is no longer needed as of Cloverage 1.2.3
