### ISSUE TITLE
Bump org.clojure/tools.reader version

### ISSUE THREAD

**Issue by leppaott** [cloverage/cloverage#319]
Could in next release someone bump the version to the latest: [org.clojure/tools.reader "1.3.4"].

We had the following error while running unit tests on CI through kaocha-cloverage plugin and adding dependency fixed it:
`class clojure.tools.reader.reader_types.IndexingPushbackReader cannot be cast to class java.io.Closeable (clojure.tools.reader.reader_types.IndexingPushbackReader is in unnamed module of loader clojure.lang.DynamicClassLoader @60ee7a51; java.io.Closeable is in module java.base of loader 'bootstrap')`

**Comment by lvh** [comment]
I'd be happy to take a PR for this (in case something else breaks).

**Comment by superwesman** [comment]
@leppaott - I'm seeing the same error, but adding tools.reader as an explicit dependency did not fix for me.  Are you sure there's nothing else at play here?

**Comment by leppaott** [comment]
@superwesman just tested without the explicit dependency on the bottom. and got the same error.
This fix on the reader seemed relevant: https://github.com/clojure/tools.reader/commit/c8981dd6ac7a560db85321b03278d03caf2aed39

Full CI logs: 
`Exception in thread "main" Syntax error compiling at (/tmp/form-init14549744393889545930.clj:1:74).
Error instrumenting consent.states.config
	at clojure.lang.Compiler.load(Compiler.java:7647)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$init_opt.invokeStatic(main.clj:454)
	at clojure.main$init_opt.invoke(main.clj:454)
	at clojure.main$initialize.invokeStatic(main.clj:485)
	at clojure.main$null_opt.invokeStatic(main.clj:519)
	at clojure.main$null_opt.invoke(main.clj:516)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: Error instrumenting consent.states.config {:lib consent.states.config, :filename "consent/states/config.clj"}
	at cloverage.instrument$instrument.invokeStatic(instrument.clj:542)
	at cloverage.instrument$instrument.invoke(instrument.clj:533)
	at cloverage.coverage$instrument_namespaces$fn__7475.invoke(coverage.clj:160)
	at cloverage.coverage$instrument_namespaces.invokeStatic(coverage.clj:155)
	at cloverage.coverage$instrument_namespaces.invoke(coverage.clj:151)
	at cloverage.coverage$run_main.invokeStatic(coverage.clj:260)
	at cloverage.coverage$run_main.invoke(coverage.clj:253)
	at kaocha.plugin.cloverage$run_cloverage.invokeStatic(cloverage.clj:152)
	at kaocha.plugin.cloverage$run_cloverage.invoke(cloverage.clj:139)
	at kaocha.plugin.cloverage$cloverage_main_hook.invokeStatic(cloverage.clj:185)
	at kaocha.plugin.cloverage$cloverage_main_hook.invoke(cloverage.clj:154)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at kaocha.plugin$run_hook_STAR_$fn__796.invoke(plugin.clj:83)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at kaocha.plugin$run_hook_STAR_.invokeStatic(plugin.clj:81)
	at kaocha.plugin$run_hook_STAR_.doInvoke(plugin.clj:80)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:671)
	at clojure.core$apply.invoke(core.clj:660)
	at kaocha.plugin$run_hook.invokeStatic(plugin.clj:92)
	at kaocha.plugin$run_hook.doInvoke(plugin.clj:91)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at kaocha.runner$run.invokeStatic(runner.clj:134)
	at kaocha.runner$run.invoke(runner.clj:76)
	at kaocha.runner$_main_STAR_.invokeStatic(runner.clj:179)
	at kaocha.runner$_main_STAR_.doInvoke(runner.clj:147)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at kaocha.runner$_main.invokeStatic(runner.clj:190)
	at kaocha.runner$_main.doInvoke(runner.clj:188)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:388)
	at user$eval140.invokeStatic(form-init14549744393889545930.clj:1)
	at user$eval140.invoke(form-init14549744393889545930.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	... 12 more
Caused by: java.lang.ClassCastException: class clojure.tools.reader.reader_types.IndexingPushbackReader cannot be cast to class java.io.Closeable (clojure.tools.reader.reader_types.IndexingPushbackReader is in unnamed module of loader clojure.lang.DynamicClassLoader @7bef7505; java.io.Closeable is in module java.base of loader 'bootstrap')
	at cloverage.instrument$instrument_file.invokeStatic(instrument.clj:527)
	at cloverage.instrument$instrument_file.invoke(instrument.clj:523)
	at cloverage.instrument$instrument.invokeStatic(instrument.clj:538)`

The suspicious code on the function is simply:
`(-> (io/resource resource)
         slurp
         edn/read-string)`
         
Using `[org.clojure/clojure "1.10.0"]
             [lambdaisland/kaocha "1.0.829"]
             [lambdaisland/kaocha-cloverage "1.0.75"]`

Other than that don't know much about it. To be clear this is only happening with kaocha-cloverage.

**Comment by lvh** [comment]
@superwesman I'd still be happy to take a PR :)
